app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('przetargi/', include('tenders.urls', namespace='tenders')),
    path('', RedirectView.as_view(url='/users/login/', permanent=True)),
    path('clients/', include('clients.urls')),
    path('specialists/', include('specialists.urls')),
    path('reports/', include('reports.urls')),
]

app/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import CustomLoginView, CustomPasswordChangeView

app_name = 'users'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

app/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordChangeForm
from core.models import User
from django.utils.translation import gettext_lazy as _

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email', 'first_name', 'last_name', 'position')
        labels = {
            'email': _('E-mail'),
            'first_name': _('Imię'),
            'last_name': _('Nazwisko'),
            'position': _('Stanowisko'),
        }

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'position')
        labels = {
            'email': _('E-mail'),
            'first_name': _('Imię'),
            'last_name': _('Nazwisko'),
            'position': _('Stanowisko'),
        }

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('email', 'password')
        labels = {
            'email': _('E-mail'),
            'password': _('Hasło'),
        }

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].help_text = ("Nowe hasło musi zawierać co najmniej 12 znaków, w tym co najmniej", 
                                                "\n- jedną cyfrę",
                                                "\n- jedną małą literę", 
                                                "\n- jedną dużą literę",
                                                "\n- jeden znak specjalny",)
    
    old_password = forms.CharField(
        label=_("Stare hasło"),
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        strip=False,
    )
    new_password1 = forms.CharField(
        label=_("Nowe hasło"),
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        strip=False,
    )
    new_password2 = forms.CharField(
        label=_("Potwierdź nowe hasło"),
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        strip=False,
    )

class Meta:
    fields = ('old_password', 'new_password1', 'new_password2')

    def clean_new_password1(self):
        password = self.cleaned_data.get('new_password1')
        if len(password) < 12:
            raise forms.ValidationError(_("Hasło musi mieć co najmniej 12 znaków."))
        if not any(char.isdigit() for char in password):
            raise forms.ValidationError(_("Hasło musi zawierać co najmniej jedną cyfrę."))
        if not any(char.islower() for char in password):
            raise forms.ValidationError(_("Hasło musi zawierać co najmniej jedną małą literę."))
        if not any(char.isupper() for char in password):
            raise forms.ValidationError(_("Hasło musi zawierać co najmniej jedną dużą literę."))
        if not any(char in '!@#$%^&*()_+-=[]{}|;:,.<>?' for char in password):
            raise forms.ValidationError(_("Hasło musi zawierać co najmniej jeden znak specjalny."))
        return password

app/users/views.py
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from .forms import CustomAuthenticationForm, CustomPasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.shortcuts import redirect
from django.contrib import messages
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.middleware.csrf import get_token
import logging

User = get_user_model()

# Konfiguracja loggera
logger = logging.getLogger(__name__)

@method_decorator(never_cache, name='dispatch')
class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'users/login.html'

    def get(self, request, *args, **kwargs):
        csrf_token = get_token(request)  
        logger.debug(f"CSRF Token on GET: {csrf_token}")
        response = super().get(request, *args, **kwargs)
        response.set_cookie('csrftoken', csrf_token)
        return response

    def form_invalid(self, form):
        messages.error(self.request, "Błędne dane logowania. Spróbuj ponownie.")
        return super().form_invalid(form)
    
    def get_success_url(self):
        user = self.request.user
        if user.password_change_due():
            return reverse_lazy('users:password_change')
        return reverse_lazy('tenders:przetargi')

class CustomPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    form_class = CustomPasswordChangeForm
    success_url = reverse_lazy('tenders:przetargi')
    template_name = 'users/password_change.html'

    def form_valid(self, form):
        logger.debug("Form is valid")
        # Debugowanie
        # logger.debug(f"Old password: {form.cleaned_data.get('old_password')}")
        # logger.debug(f"New password1: {form.cleaned_data.get('new_password1')}")
        # logger.debug(f"New password2: {form.cleaned_data.get('new_password2')}")

        # Sprawdzenie zgodności haseł
        new_password1 = form.cleaned_data.get('new_password1')
        new_password2 = form.cleaned_data.get('new_password2')
        if new_password1 != new_password2:
            messages.error(self.request, "Hasła nie są zgodne.")
            return self.form_invalid(form)

        response = super().form_valid(form)
        self.request.user.password_change_date = timezone.now()
        self.request.user.save()
        return response

    def form_invalid(self, form):
        errors = form.errors.as_text()
        logger.error(f"Form errors: {errors}")
        messages.error(self.request, f"Wystąpił błąd podczas zmiany hasła. {errors}")
        return super().form_invalid(form)

app/users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logowanie</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #F8F9FA;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .login-container {
            background-color: #FFFFFF;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            text-align: center;
            max-width: 90%; 
        }
        .logo img {
            width: 100px;
            height: 100px;
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 15px;
            text-align: left;
        }
        label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
            color: #333333;
        }
        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #CCCCCC;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 14px;
        }
        input[type="text"]:focus,
        input[type="password"]:focus {
            outline: none;
            border-color: #1F4D8E;
        }
        .btn {
            width: 100%;
            padding: 10px;
            background-color: #1F4D8E;
            color: #FFFFFF;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
        }
        .btn:hover {
            background-color: #E0F2F1;
            color: #333333;
        }
        .btn:active {
            background-color: #1F4D8E;
            color: #FFFFFF;
        }
        .btn:disabled {
            background-color: #D3D3D3;
            color: #666666;
            cursor: not-allowed;
        }
    </style>
</head>
<body>
    <div class="login-container">
        <div class="logo">
            <img src="{% static 'images/logo.png' %}" alt="FSNT NOT Płock">
        </div>
        {% if messages %}
            <div class="error-message">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">e-mail:</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label for="password">hasło:</label>
                {{ form.password }}
            </div>
            <button type="submit" class="btn">Zaloguj się</button>
        </form>
        
    </div>
</body>
</html>

app/users/templates/users/password_change.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zmiana hasła</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #F8F9FA;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .change-password-container {
            background-color: #FFFFFF;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            text-align: center;
            max-width: 90%;
        }
        .logo img {
            width: 100px;
            height: 100px;
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 15px;
            text-align: left;
        }
        label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
            color: #333333;
        }
        input[type="password"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #CCCCCC;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 14px;
        }
        input[type="password"]:focus {
            outline: none;
            border-color: #1F4D8E;
        }
        .btn {
            width: 100%;
            padding: 10px;
            background-color: #1F4D8E;
            color: #FFFFFF;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
        }
        .btn:hover {
            background-color: #E0F2F1;
            color: #333333;
        }
        .btn:active {
            background-color: #1F4D8E;
            color: #FFFFFF;
        }
        .btn:disabled {
            background-color: #D3D3D3;
            color: #666666;
            cursor: not-allowed;
        }
        .messages {
            margin-bottom: 20px;
        }
        .messages .error {
            color: red;
        }
        .messages .success {
            color: green;
        }

        
    </style>
</head>
<body>
    <div class="change-password-container">
        <div class="logo">
            <img src="{% static 'images/logo.png' %}" alt="Logo">
        </div>
        {% if form.errors %}
        <div class="messages">
            <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li class="error">{{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="info-message">
                <p>Nowe hasło musi zawierać co najmniej 12 znaków, w tym co najmniej:<br>
                jedną cyfrę, jedną małą literę, jedną dużą literę, jeden znak specjalny.</p>
            </div>
            <div class="form-group">
                <label for="id_old_password">Stare hasło:</label>
                {{ form.old_password }}
            </div>
            <div class="form-group">
                <label for="id_new_password1">Nowe hasło:</label>
                {{ form.new_password1 }}
            </div>
            <div class="form-group">
                <label for="id_new_password2">Potwierdź nowe hasło:</label>
                {{ form.new_password2 }}
            </div>
            <button type="submit" class="btn">Zmień hasło</button>
        </form>
    </div>    
</body>
</html>